### ISSUE TITLE
asmcli script fails with enable_all option with a separate fleet project that has meshconfig API disabled

### ISSUE THREAD

**Issue by jwmcelr** [GoogleCloudPlatform/anthos-service-mesh-packages#1091]
### Scenario
Running asmcli 1.12, with a normal in-cluster control plane. GKE cluster is in one project, and Fleet is in a separate project. Script gets 403 trying to initialize meshconfig with enable-all flag passed in.

### Issue Description
I'm very new to ASM, so not 100% sure I'm not doing something wrong, but I think I found an issue with the asmcli script. I was running into an issue where the asmcli script would crash with a 403 trying to run a curl against https://meshconfig.googleapis.com, i.e.:

`curl --request POST --fail --data "{\"workloadIdentityPools\":[\"${FleetProjectID}.hub.id.goog\",\"${FleetProjectID}.svc.id.goog\"]}" -o /dev/null https://meshconfig.googleapis.com/v1alpha1/projects${FleetProjectID}:initialize... headers ...`

And it would do this repeatedly every time I ran it. And if I ran the curl command manually (after subbing in the correct Authorization header with the auth token) it would also fail with a 403. At first I thought there was some permission missing somehow but then I traced it through and figured out that it was because the meshconfig API in the fleet project was disabled. Once I enabled it manually, it worked. 

### Suspect Code?

I think the issue is here:

```
enable_gcloud_apis(){
  local PROJECT_ID; PROJECT_ID="$(context_get-option "PROJECT_ID")"
  local FLEET_ID; FLEET_ID="$(context_get-option "FLEET_ID")"

  info "Enabling required APIs..."
  # shellcheck disable=SC2046
  retry 3 gcloud services enable --project="${PROJECT_ID}" $(required_apis | tr '\n' ' ')

  if [[ "${FLEET_ID}" != "${PROJECT_ID}" ]]; then
    local REQUIRED_FLEET_APIS; REQUIRED_FLEET_APIS="$(required_fleet_apis | tr '\n' ' ')"
    if [[ -n "${REQUIRED_FLEET_APIS// }" ]]; then
      # shellcheck disable=SC2086
      retry 3 gcloud services enable --project="${FLEET_ID}" ${REQUIRED_FLEET_APIS}
    fi
  fi
}
```

Note how if the fleet project is different from the GKE cluster project it only enables REQUIRED_FLEET_APIS in the fleet project. And the apis returned by the required_fleet_apis function does not include meshconfig:

```
required_fleet_apis() {
  local CA; CA="$(context_get-option "CA")"
  case "${CA}" in
   mesh_ca)
     echo meshca.googleapis.com
     ;;
   gcp_cas)
     echo privateca.googleapis.com
     ;;
    *);;
  esac
}
```

I'm guessing some people in this scenario would have already enabled the meshconfig API in the separate project another way, but I was relying on the script to do it.

**Comment by zerobfd** [comment]
Thank you for the report! That definitely looks like the culprit. I'll have a PR out shortly.

**Comment by zerobfd** [comment]
Out of curiosity, what CA are you using for this installation?

**Comment by jwmcelr** [comment]
The default. Mesh-ca if I remember right.

**Comment by jwmcelr** [comment]
Confirmed it is mesh-ca

**Comment by zerobfd** [comment]
Thanks for confirming. My best guess is that something changed behind the scenes with what APIs automatically enable other APIs, since I know this worked at one point. The attached PR should fix it though.
