### ISSUE TITLE
Remove monitoring and iamcredentials from services list as they appear redundant

### ISSUE THREAD

**Issue by davidebbo** [GoogleCloudPlatform/anthos-service-mesh-packages#11]
Unless we know of a reason not to...

**Comment by tangiel** [comment]
I created a new public project and it didn't have iamcredentials enabled.

**Comment by davidebbo** [comment]
Ok, I just removed monitoring (and added stackdriver). bb199ca52e88bdd0f19652e6d00eb438e540cc4e
