### ISSUE TITLE
Failed clone git repo: trouble hard resetting empty repository to "1.12.5-asm.0+config3

### ISSUE THREAD

**Issue by kristaum** [GoogleCloudPlatform/anthos-service-mesh-packages#1205]
We already installed a couple of cluster with Anthos but suddenly this afternoon we start getting this error.
Checking the tags that doesn't seems to exist indeed...
But I'm running asmcli and from what I saw I cannot specify this piece "asm.0+config3"

Any advice?

**Comment by kristaum** [comment]
Found that asmcli fetched from https://storage.googleapis.com/csm-artifacts/asm/asmcli was setting incorrect config version to 3.
To circumvent that got the asmcli from this repository here.

**Comment by zerobfd** [comment]
Glad that you found a workaround, but thought I'd follow up with some more details:

There are three different versions of `asmcli` published: `asmcli` is the latest version, `asmcli_1.x` is the latest version of the 1.x ASM minor version, and there are also specific versions per `asmcli` release. For example:

https://storage.googleapis.com/csm-artifacts/asm/asmcli is 1.13 at the time of writing
https://storage.googleapis.com/csm-artifacts/asm/asmcli_1.12 is the latest version that installs ASM 1.2
https://storage.googleapis.com/csm-artifacts/asm/asmcli_1.12.5-asm.0-config2 is the version that corresponds to the specific tag in this repo

https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/main/docs/versioning.md has some more details on how the versioning works. You can also see https://storage.googleapis.com/csm-artifacts/asm/ASMCLI_VERSIONS for all of the versions available at a given time: the format is `${VERSION}:${FILENAME}`, where `$FILENAME` is the thing that comes after https://storage.googleapis.com/csm-artifacts/asm/

However, you're welcome to keep getting a specific version via `git` if that's more convenient.

**Comment by kristaum** [comment]
Awesome! Thanks for the extra input, it helped a lot understanding.
We were installing 1.12.5 but using https://storage.googleapis.com/csm-artifacts/asm/asmcli_1.12 
It seems that the CONFIG_VER var got updated to 3 and hence giving us the error.
Good to know there is a way to fetch asmcli_1.12.5-asm.0-config2 directly from the storage googleapis url.
