### ISSUE TITLE
asmcli install: GKE cluster gets registered with name null

### ISSUE THREAD

**Issue by mhofstetter** [GoogleCloudPlatform/anthos-service-mesh-packages#1294]
Starting with 1.14.1-asm.3+config5, installing ASM to a GKE cluster results in a registration with the name `null` to the Anthos Fleet. This might result in failing ASM installations due to duplicated names.

```
asmcli install --enable_all [...]
...
asmcli: Registering the cluster as null...
asmcli: [WARNING]: Failed, retrying...(1 of 2)
asmcli: [WARNING]: Failed, retrying...(2 of 2)
asmcli: [WARNING]: Command 'run_command gcloud container hub memberships register null [...] failed
```

It seems as the bug has been introduced with https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/pull/1258 where the context-key `MEMBERSHIP_NAME` is used - which doesn't exist in the default context (https://github.com/zerobfd/anthos-service-mesh-packages/blob/b01078864136b174b3f4380abbc86182c2cb72d1/asmcli/asmcli#L3188). 

This results in a jq lookup of `null` which gets returned as membership name (https://github.com/zerobfd/anthos-service-mesh-packages/blob/b01078864136b174b3f4380abbc86182c2cb72d1/asmcli/asmcli#L3713)

**Comment by zerobfd** [comment]
Thanks! Somewhere in the mess of cherry-picking on release branches the fix for this was missed, sorry for this! I'll merge and release a new version as soon as tests pass.

**Comment by zerobfd** [comment]
+config6 version is rolling out now with the fix. Thanks again for the report!
