### ISSUE TITLE
Allow GitOps integration

### ISSUE THREAD

**Issue by therealmitchconnors** [GoogleCloudPlatform/anthos-service-mesh-packages#169]
Currently, the script generates and installs ASM config, which is not suitable for GitOps integration.  Ideally, users should treat their config as code, and review a diff of all changes before deploying to production via GitOps.  I think all that is needed here is a way to dump the config to stdout instead of applying it directly.

**Comment by zerobfd** [comment]
I was thinking about this and realized this might not have been what you wanted. The PR prints the config from this repo as-is, i.e. without passing it through `istioctl manifest generate`. Is that your intent and/or do you know whether people would prefer dry or hydrated configs at this step in the pipeline?

**Comment by zerobfd** [comment]
Chatted offline, going with dry for now and if someone expresses interest we can figure out how to support both.
