### ISSUE TITLE
add_cluster_labels function fails in install_asm script

### ISSUE THREAD

**Issue by imrannayer** [GoogleCloudPlatform/anthos-service-mesh-packages#256]
[install_asm](https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/release-1.7-asm/scripts/asm-installer/install_asm) script retrieves existing labels and applies them back with some more labels. Labels retrieve by `gcloud container clusters describe` command returns values separated by semicolons. When the script executes `gcloud container clusters update` with some values separated by semicolons it fails. Values should be separated by comma.

**Comment by zerobfd** [comment]
Thank you for letting us know!
