### ISSUE TITLE
Release 1.6 is the last installable release through Terraform

### ISSUE THREAD

**Issue by NightmareCinema** [GoogleCloudPlatform/anthos-service-mesh-packages#359]
Any version branch/tag beyond 1.6 is uninstallable via Terraform using the official asm module (https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/asm) due to missing `asm-patch` directory and its content.

**Comment by zerobfd** [comment]
I'm fairly sure there are several more issues other than just `asm-patch` being unavailable. The install process has changed considerably from 1.6 to 1.8.

There's not much we can do on the configuration side, we only guarantee compatibility within a minor version. I'd suggest opening an issue/PR on the TF repo to support later versions. There's an open issue to try and use the newer install script with the TF module (https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/707) but unfortunately no one has had time to look at it yet.

**Comment by zerobfd** [comment]
This has been updated.
