### ISSUE TITLE
clusterrolebinding name should be unique

### ISSUE THREAD

**Issue by zerobfd** [GoogleCloudPlatform/anthos-service-mesh-packages#377]
"cluster-admin-binding" is generic and could overwrite something unintentionally. install_asm should prefix it with the username.

**Comment by ShrillShrestha** [comment]
Hi @zerobfd, I am new to open source and am learning to contribute. I think this can be a good issue for me to work on. If you can guide me and provide a bit more info regarding the issue, I might be able to work on it.

**Comment by zerobfd** [comment]
Sure! In scripts/asm_installer/install_asm there are several functions that handle dependencies. One of them, `bind_user_to_cluster_admin`, creates a clusterrolebinding in the cluster to make the current user an admin so they can install properly.

Right now it always uses the name `cluster-admin-binding` for the k8s object, which means that if you run `install_asm` several times in a row with different users, the clusterrolebinding will get overwritten every time. To prevent this we can prefix the name of the resource with some information about the user. The user is of the form "something@domain", so splitting that on the @ and taking the left side to get the username part of it seems like a reasonable prefix, and then we can use `${USER}-cluster-admin-binding` instead.

**Comment by ShrillShrestha** [comment]
> The user is of the form "something@domain", so splitting that on the @ and taking the left side to get the username part of it seems like a reasonable prefix, 

Are we passing users as a CLI argument? And saving the left part in the `USER` variable.

> and then we can use `${USER}-cluster-admin-binding` instead.

How do we implement it? do I just rename 
https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/ef60c226a13a90442051e1f676b4b78bf8decbb8/scripts/asm-installer/install_asm#L1823

to
`${USER}-cluster-admin-binding`

Please forgive my novice question, I haven't used a bash script much.

**Comment by zerobfd** [comment]
The user information we pull from `gcloud config get-value core/account` at the top of the function. Implementing it can be done using `cut`, something like `PREFIX="$(echo "${GCLOUD_USER}" | cut -f 2 -d @)"` and then change the kubectl arguments to use `clusterrolebinding "${PREFIX}-cluster-admin-binding" \`.

**Comment by zerobfd** [comment]
Thank you!
