### ISSUE TITLE
Too many roles are assigned on istiod service account 

### ISSUE THREAD

**Issue by cagataygurturk** [GoogleCloudPlatform/anthos-service-mesh-packages#420]
The following line

https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/8337ba1608557b30a8e5b549c9f6089a08b74acb/scripts/asm-installer/install_asm#L190

attempts to add the following IAM roles on the managed istiod service account:

```
roles/servicemanagement.admin
roles/serviceusage.serviceUsageAdmin
roles/meshconfig.admin
roles/compute.admin
roles/container.admin
roles/resourcemanager.projectIamAdmin
roles/iam.serviceAccountAdmin
roles/iam.serviceAccountKeyAdmin
roles/gkehub.admin
roles/privateca.admin
```

These roles are the same roles that the local IAM user needs to do many things. I highly doubt the managed istiod SA requires such extensive roles on user's project like `resourcemanager.projectIamAdmin` or `compute.admin`. In fact I was able to verify that without at least `resourcemanager.projectIamAdmin`, things work fine. Can these roles be reviewed?

**Comment by zerobfd** [comment]
These were pared down significantly and only required conditionally.
