### ISSUE TITLE
Add anthos.googleapis.com to required services

### ISSUE THREAD

**Issue by cagataygurturk** [GoogleCloudPlatform/anthos-service-mesh-packages#423]
Anthos Service Mesh dashboards are not visible in the Cloud Console until anthos.googleapis.com is enabled. Since only enabling API does not trigger Anthos subscription, it could be considered to enable the Anthos API by default.

**Comment by zerobfd** [comment]
Thanks. I'll confirm internally--I remember there was some concern on whether this was always safe but I don't remember exactly what came out of that conversation.

**Comment by zerobfd** [comment]
I want to confirm if you remember: according to here https://cloud.google.com/service-mesh/docs/ui-differences there are UI differences depending on whether the API is enabled or not. Before you enabled the UI, none of the service dashboards were working?

**Comment by cagataygurturk** [comment]
Correct, before enabling the API there is no Anthos tab on the UI that also contains Service Mesh.

**Comment by zerobfd** [comment]
I believe we root caused this to something else and updated the documentation. If this is still an issue reach out via Cloud support. This API shouldn't be required.
