### ISSUE TITLE
ASM 1.9 not showing warning "Dependency not found: kpt"

### ISSUE THREAD

**Issue by murphye** [GoogleCloudPlatform/anthos-service-mesh-packages#539]
I am running the latest install_asm and getting this error. There is a Not Found error for `https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages.git/asm@release-1.9-asm`

```
install_asm: Downloading ASM kpt package...
install_asm: Running: ' pkg get --auto-set=false https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages.git/asm@release-1.9-asm asm'
install_asm: -------------
./install_asm: line 346: : command not found
install_asm: [WARNING]: Failed, retrying...(1 of 3)
install_asm: Running: ' pkg get --auto-set=false https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages.git/asm@release-1.9-asm asm'
install_asm: -------------
./install_asm: line 346: : command not found
install_asm: [WARNING]: Failed, retrying...(2 of 3)
install_asm: Running: ' pkg get --auto-set=false https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages.git/asm@release-1.9-asm asm'
install_asm: -------------
./install_asm: line 346: : command not found
install_asm: [WARNING]: Failed, retrying...(3 of 3)
```

**Comment by murphye** [comment]
Used this command to retrieve the script `curl https://storage.googleapis.com/csm-artifacts/asm/install_asm_1.9 > install_asm`

**Comment by murphye** [comment]
Update:

The problem was I need to run `gcloud components install kpt`

The 1.8.3 script gave me a warning `Dependency not found: kpt`. I did not see this for 1.9.

**Comment by zerobfd** [comment]
Thanks for reporting! If you'd like to test this before the next release, it's been merged into the pre-production version at https://storage.googleapis.com/csm-artifacts/asm/install_asm_staging_1.9
