### ISSUE TITLE
is_user_cluster_admin check fails if only Google IAM role is given

### ISSUE THREAD

**Issue by sebastian-a-neb-db** [GoogleCloudPlatform/anthos-service-mesh-packages#588]
Hey everyone,
we have a service account running the `install_asm` script. The Service account itself has the Google Cloud IAM role `roles/container.admin` which is listed as requirement [here](https://cloud.google.com/service-mesh/docs/installation-permissions). This means that this service account is cluster-admin in the cluster and can change all API objects within the cluster. Nevertheless the check `is_user_cluster_admin` in the `install_asm` script only checks for clusterrolebindings within the cluster and therefore this check fails.

This is in my opinion a bad behaviour. The check should not fail if the service account has the Google Cloud IAM `roles/container.admin` role.

Any other opinions on this or any chance to fix this?

**Comment by sebastian-a-neb-db** [comment]
Apart from that: I tried validating the installation with `--only_validate` and still could see the log lines:

```bash
install_asm: Creating istio-system namespace...
namespace/istio-system created
```

I would not expect any changes on the cluster and therefore a creation of the `istio-system` namespace with the `--only_validate` flag.

**Comment by zerobfd** [comment]
That's a good point about the IAM roles, thanks for reporting.

The `istio-system` bug just got fixed in #583, and will be in the next release.

**Comment by sebastian-a-neb-db** [comment]
Thanks for the quick reply and the PR. Looking forward for the fix :)

**Comment by zerobfd** [comment]
This was released in the last batch a couple of days ago. Thanks again for reporting!
