### ISSUE TITLE
Switch to the newest asm version when it's available

### ISSUE THREAD

**Issue by davidebbo** [GoogleCloudPlatform/anthos-service-mesh-packages#6]
`tag: 1.4.2-asm.2` will soon need to be updated.

**Comment by tangiel** [comment]
This probably shouldn't be done in this repo. Need to update the CLI.

**Comment by davidebbo** [comment]
I think it's both. In addition to the CLI changes, the tag in the ICP needs to change, which is what this is tracking. Right?

**Comment by tangiel** [comment]
You're right, forgot we had to do this.

**Comment by davidebbo** [comment]
Come to think of it, the asm profile should come with the default hub/tag values that match the istioctl build. Though as I recall, due to the CLI build process, we're not inheriting the right values, hence the need for explicit override in our ICP.

**Comment by zerobfd** [comment]
Not super familiar with the context, but I'm pretty sure the relevant parts have been fixed. Feel free to re-open if there's still an issue.
