### ISSUE TITLE
ENVIRON_PROJECT_ID is not set correctly on MacOS

### ISSUE THREAD

**Issue by YpNo** [GoogleCloudPlatform/anthos-service-mesh-packages#661]
Hi,

The "sed" command to retrieve project id from workload identity doesn't works on MacOS.

Line 2117: 
`ENVIRON_PROJECT_ID="$(kubectl get memberships.hub.gke.io membership -o=json | jq .spec.workload_identity_pool | sed 's/^\"\(.*\).\(svc\|hub\).id.goog\"$/\1/g')"`

Output on MacOS: "<my_project_id>.svc.id.goog" instead of "<my_project_id>".

To resolve it, I purpose the following sed which works on MacOS and Linux:
`ENVIRON_PROJECT_ID="$(kubectl get memberships.hub.gke.io membership -o=json | jq .spec.workload_identity_pool | sed -E 's/^\"(.*)\.(svc|hub)\.id\.goog\"$/\1/')"`

Tested with latest install_asm script and version 1.9.3-2 of ASM

Regards.

**Comment by zerobfd** [comment]
I think this issue was fixed by the merged commit? I thought it would auto-close. Please re-open if it's still an issue.
