### ISSUE TITLE
install fails on kpg anthos-service-mesh-packages step

### ISSUE THREAD

**Issue by withnale** [GoogleCloudPlatform/anthos-service-mesh-packages#797]
Whenever I try to install version 1.10.2-asm.3 as per the 'getting started' documentation...

```
./install_asm --cluster_name CLUSTER  --cluster_location LOCATION --project_id PROJECT --mode install --enable_all  --output_dir ./asm-downloads
```

I get the following errors

```
install_asm: Downloading ASM kpt package...
install_asm: [WARNING]: Failed, retrying...(1 of 3)
install_asm: [WARNING]: Failed, retrying...(2 of 3)
install_asm: [WARNING]: Failed, retrying...(3 of 3)
```

Running the script with `-x` I can see that the following line continually fails.

```
kpt pkg get --auto-set=false https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages.git/asm@1.10.2-asm.3+config1 asm
```

It seems strange that the download doesn't work since it looks pretty straightforward. Any ideas?

**Comment by zerobfd** [comment]
Hmm. That command works for me if I copy/paste it. The two things that come to mind are 1) no network connectivity to GitHub, or 2) the `asm-downloads` directory already exists and for some reason `install_asm` had trouble reporting the correct error message.

If you run it with a different output directory does it still fail?

**Comment by withnale** [comment]
Thanks. Now you've confirmed it works I've gone back.

It's all the corporate build crap our company puts on our laptops. I've just run the same command as before but within a docker container and it's fine. I'll close- thanks
